[tool.poetry]
name = "makeweb"
version = "0.1.0"
description = "Make interactive web apps using good ol' HTML, CSS and a sprinkling of JavaScript — in Python."
authors = ["Harshad Sharma <harshad@sharma.io>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
